### ISSUE TITLE
prices variants not load

### ISSUE THREAD

**Issue by key6** [pledra/odoo-product-configurator#15] opened 2017-01-18 14:45 UTC
hi i have a product with many variants. All variants has a price. the main Product have zero price. the normal website with no extension has price and show it. if i activate the configurator, the price in varaints are zero !! and on the website zero !!
what can i do?
(picture is example with mainprodukt 1 euro and every variant lot of more money - the second picture show the problem that different variants all have automatic price from mainproduct. not from variants! 
![unbenannt](https://cloud.githubusercontent.com/assets/4243514/22068354/0f2da892-dd95-11e6-9255-b35f07cdeac5.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/4243514/22068355/0f301d02-dd95-11e6-9d58-a38c76575d2b.png)

**Comment by PCatinean** [comment] 2017-01-22 17:01
@key6 I figured that the best way to answer this was to update the documentation and then link you to it:
https://www.pledra.com/odoo-product-configurator/documentation/functional/pricing.html
https://www.pledra.com/odoo-product-configurator/documentation/technical/pricing.html#pricing-technical

In short, if you want to keep the exact same pricing scheme, create products for each attribute value with price_extra, link them to the attribute values, set the price of the product the same as the price_extra.

Option two is overriding the method computing the extra price: https://github.com/pledra/odoo-product-configurator/blob/10.0/product_configurator/models/product.py#L437

**Comment by PCatinean** [comment] 2017-01-25 06:32
I will close this issue until further notice. Feel free to re-open if the issue is not solved.

**Closed as completed by PCatinean** 2017-01-25 06:32 UTC
