### ISSUE TITLE
As options are selected, choices are not shown on the WebSite

### ISSUE THREAD

**Issue by vishmehra** [pledra/odoo-product-configurator#90] opened 2017-05-02 07:51 UTC
Impacted versions: 10

Steps to reproduce: Create the product configurator and use the website to start the selection process....
![snip20170502_10](https://cloud.githubusercontent.com/assets/14320919/25608836/2d165d42-2ee2-11e7-8ba9-8909f94e2823.png)
![snip20170502_11](https://cloud.githubusercontent.com/assets/14320919/25608840/2f8dd3c0-2ee2-11e7-8d74-fef2b3202799.png)
![snip20170502_12](https://cloud.githubusercontent.com/assets/14320919/25608845/34286256-2ee2-11e7-8f13-76d2ebb87cee.png)

Current behavior:

Expected behavior: As the product configurator options are selected, they should show up in the next step. 

Video/Screenshot link (optional):

**Comment by PCatinean** [comment] 2017-05-03 13:01
Duplicate of https://github.com/pledra/odoo-product-configurator/issues/14

**Closed as completed by PCatinean** 2017-05-03 13:01 UTC
Labels: duplicate

**Comment by vishmehra** [comment] 2017-05-05 11:01
I don't think this is a duplicate.

**Comment by PCatinean** [comment] 2017-05-05 13:17
@vishmehra you're right on second look it's not a duplicate but it's not using the demo data either.

Only fresh database with demo data for bug reports I'm afraid
