### ISSUE TITLE
decimal separator issue with configurable products or product variants

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#10] opened 2017-01-12 13:26 UTC
If i have selected as a website buyer language like german the product price in ecommerce shop should be presented like 1.500,00 € instead of 1500.00 € due to the german de_DE language settings (thousands_sep => "." and decimal_point => ",")

In fact Odoo itself is affected by the same error if i would like to buy a product with standard odoo variants. There seems to be again another fix available
https://github.com/odoo-dev/odoo/commit/154428ffdf187984b683030421803614af424d7f

Unfortunately there are many linked errors and fixes trying to solve that issue for product variants. 
I don't know if there is any commit which would also fix the issue with decimal separator and language specific currency format for configurable products.

**Comment by PCatinean** [comment] 2017-01-15 19:13
@tv-openbig thank you for reporting and providing the extra information.

It should now obey all the settings in the backend for language and currency.

Please see 31db86eaa587089573d63c19aa07eca34073b9bc for more details.

Let me know if the issue is fixed so that I can close it.

**Comment by PCatinean** [comment] 2017-01-21 14:35
@tv-openbig until further notice I will consider this issue resolved. Feel free to re-open if you consider otherwise

**Comment by tv-openbig** [comment] 2017-01-24 08:35
Hello Paul,

i assume it is the same bug: https://github.com/pledra/odoo-product-configurator/issues/12

I have updated the module and indeed the issue is only partly fixed.
Still remaining issue is, if you open your configurable product:
<img width="1204" alt="bildschirmfoto 2017-01-24 um 09 26 30" src="https://cloud.githubusercontent.com/assets/8348598/22239637/cf17825a-e217-11e6-928e-da0b94d06d5f.png">

If you have selected a value the formatting is OK:
<img width="1202" alt="bildschirmfoto 2017-01-24 um 09 26 46" src="https://cloud.githubusercontent.com/assets/8348598/22239659/eb6ecb5c-e217-11e6-90af-a75c6c69e3fc.png">

If you move on to the next step the issue comes back again:
<img width="1180" alt="bildschirmfoto 2017-01-24 um 09 27 09" src="https://cloud.githubusercontent.com/assets/8348598/22239675/007034e6-e218-11e6-9919-5c243eea4fa0.png">

Again if you select a value on this step the formatting is OK:
<img width="1245" alt="bildschirmfoto 2017-01-24 um 09 27 21" src="https://cloud.githubusercontent.com/assets/8348598/22239704/1250813e-e218-11e6-89db-f78c257e5941.png">

**Comment by wouterdestecker** [comment] 2017-01-24 23:09
Dear Paul,

not sure if this matters:
When I installed the product configurator to a clean installed Odoo10, it
renamed all my pricelists into "Public Pricelist"

see
https://www.dropbox.com/s/tpjaw5dbj558rvf/Schermafdruk%202017-01-25%2000.06.12.png?dl=0
for a screenshot.

kind regards,

Wouter

**Comment by PCatinean** [comment] 2017-01-25 06:18
@tv-openbig i'm still having problems reproducing this bug locally with demo data.

Just to make sure, did you update both product-configurator and wesbsite-product-configurator modules?

I tried changing the views, updating options randomly, clicking on the separate steps and the price stays consistent all over.

Can you locate the bug with the demo data in a fresh instance to help me reproduce?

**Comment by PCatinean** [comment] 2017-01-25 06:19
@wouterdestecker I installed a fresh database for V10 and installed the configurator modules directly. I did not experience this problem.

Do you have some clear steps to reproduce the bug? If so please feel free to open a new issue

**Comment by PCatinean** [comment] 2017-01-29 16:41
@tv-openbig if you have used the website editor previous to the decimal fix, the view is frozen with noupdate=True.

Please make sure the website_product_configurator.product_configurator view has this line
`<t t-set="prices" t-value="product_tmpl.get_cfg_price(cfg_val_ids.ids, **formatLang=True**)"/>`

with the extra kwarg formatLang="True"

**Comment by PCatinean** [comment] 2017-01-29 20:16
I will again close the issue until further notice. If it's still not solved please feel free to reopen it.

**Closed as completed by PCatinean** 2017-01-29 20:16 UTC
Labels: bug

**Comment by tv-openbig** [comment] 2017-02-06 14:58
The issue could be fixed by adding the extra kwarg formatLang="True" as you suggested.
